### ISSUE TITLE
Post editing issues

### ISSUE THREAD

**Issue by vaniver** [tricycle/lesswrong#585]
It looks like lesswrong.com/submit gives a 404 when editing a post that's supposed to go to Main (with admin on). It's likely this is related to [PR 575](https://github.com/tricycle/lesswrong/pull/575).

**Comment by jglamine** [comment]
I'll take a look at this now.

**Comment by jglamine** [comment]
I'm able to reproduce this locally.

Editing of articles is broken, both on main and discussion.
Submission to main works fine.

**Comment by jglamine** [comment]
Found it.

The bug was caused by a JavaScript error. When the page loads, it tries to add some help text to the "url" filed. But on the edit page there is no "url" field. So it throws an exception and never binds the onSubmit handler for the form.

That's why it's posting to /submit instead of making an xhr request to /api/submit.

**Comment by vipulnaik** [comment]
I see you have a commit fixing the issue; but I still can't edit old posts. Is the commit just awaiting deployment, or is there more debugging you need to do?

**Comment by jglamine** [comment]
Still waiting on deployment. I'd recommend watching PR #586 if you want to be notified when it's deployed.

**Comment by wezm** [comment]
Fix deployed. Sorry about the delay we had a public holiday then I was off sick.
